app/models/__init__.py
from app.models.user import User
from app.models.post import Post
from app.models.comment import Comment
from app.models.category import Category

app/models/category.py
from app.extensions import db

class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(600))

app/models/comment.py
from app.extensions import db

class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())

app/models/post.py
from app.extensions import db

class Post(db.Model):
    __tablename__ = 'post'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    author_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    created_at = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, default=None)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=True)

app/models/user.py
from app.extensions import db

class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    phone_number = db.Column(db.String(20), nullable=False)
    address = db.Column(db.String(255), nullable=False)
    date_of_birth = db.Column(db.Date, nullable=False)
    role = db.Column(db.String(50), nullable=False, default='client')
    created_at = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    updated_at = db.Column(db.DateTime, default=None)

    def __repr__(self):
        return f'<User "{self.username}">'

app/__init__.py
from flask import Flask, g
from flask_migrate import Migrate

from config import Config
from app.extensions import db

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Initialize Flask extensions here
    db.init_app(app)
    migrate = Migrate(app, db)

    from app.models import User, Post, Comment, Category

    # Register blueprints here
    from app.main import bp as main_bp
    from app.auth import bp as auth_bp
    from app.blog import bp as blog_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(blog_bp, url_prefix='/blog')

    @app.route('/test')
    def test_page():
        return '<h1>Testing the Flask Application Factory Pattern</h1>'

    return app

app/blog/__init__.py
from flask import Blueprint, current_app
from app.models import Category
from app.extensions import db

bp = Blueprint('blog', __name__)

from app.blog import routes

@bp.app_context_processor
def inject_categories():
    categories = Category.query.all()
    return dict(categories=categories)

@bp.before_app_request
def create_categories():
    with current_app.app_context():
        if not Category.query.first():
            categories = [
                'World',
                'Technology',
                'Design',
                'Culture',
                'Business',
                'Politics',
                'Opinion',
                'Science',
                'Health',
                'Style',
                'Travel',
                'Fitness',
            ]

            for category_name in categories:
                category = Category(name=category_name)
                db.session.add(category)

            db.session.commit()

app/blog/routes.py
from flask import render_template, request, g, flash, abort, redirect, url_for
from app.blog import bp
from app.extensions import db
from app.models import Category, Post, User, Comment
from app.auth import login_required
from app.helpers import row_to_dict

from datetime import datetime

@bp.route('/home')
def home():
    return render_template('blog/home.html')

@bp.route('/categories/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    posts = Post.query.filter_by(category_id=category_id)
    return render_template('blog/category.html', category=category, posts=posts)

@bp.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        category = int(request.form['category'])

        post = Post(
            title = title,
            content = content,
            author_id = g.user.id,
            category_id = category
        )

        db.session.add(post)
        db.session.commit()

        flash('The post was created successfully.')

        return redirect(url_for('blog.show_user_posts', username=g.user.username))

    return render_template('blog/new_post.html')

@bp.route('/users/<string:username>')
def show_user_posts(username):
    user = User.query.filter_by(username=username).first()
    if not user:
        abort(404)

    user_posts = Post.query.filter_by(author_id=user.id)
    user_posts_dicts = []
    for user_post in user_posts:
        user_post = row_to_dict(user_post)
        category = Category.query.get_or_404(user_post['category_id'])
        user_post['category'] = category.name
        user_posts_dicts.append(user_post)

    return render_template('blog/user_posts.html', user_posts=user_posts_dicts)

@bp.route('/post/<int:post_id>')
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    author = User.query.get_or_404(post.author_id)

    comments = Comment.query.filter_by(post_id=post.id)
    comments_dicts = []
    for comment in comments:
        user = User.query.get_or_404(comment.author_id)
        comment = row_to_dict(comment)
        comment['author_username'] = user.username
        comments_dicts.append(comment)

    comments_dicts.reverse()

    return render_template('blog/post.html', post=post, author=author, comments=comments_dicts)

@bp.route('/edit_post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        category = int(request.form['category'])

        post.title = title
        post.content = content
        post.category_id = category
        post.updated_at = datetime.utcnow()

        db.session.commit()

        flash('The post has been successfully updated.')

    return render_template('blog/edit_post.html', post=post)

@bp.route('/delete_post/<int:post_id>')
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    comments = Comment.query.filter_by(post_id=post.id).all()
    for comment in comments:
        db.session.delete(comment)

    db.session.delete(post)
    db.session.commit()

    flash('The post has been successfully deleted.')

    return redirect(url_for('blog.show_user_posts', username=g.user.username))

@bp.route('/add_comment/<int:post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    content = request.form['comment']

    new_comment = Comment(
        content = content,
        author_id = g.user.id,
        post_id = post_id,
    )

    db.session.add(new_comment)
    db.session.commit()

    return redirect(url_for('blog.show_post', post_id=post_id))

app/main/__init__.py
from flask import Blueprint, g

bp = Blueprint('main', __name__)

from app.main import routes, errors

app/main/routes.py
from flask import render_template, redirect, url_for
from app.main import bp
from app.auth import login_required

@bp.route('/')
def index():
    return redirect(url_for('auth.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon.png') }}">
    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Custom css-->
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block custom_css %}{% endblock %}
    <!-- Font awesome -->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>

<div class="container">
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-8 pt-1">
        <a class="link-secondary text-decoration-none" href="{{ url_for('blog.home') }}">
          <i class="fa-solid fa-blog"></i>
          Blog</a>
      </div>


      {% if user %}
       <div class="col-4 d-flex justify-content-end align-items-center">
        <div class="dropdown">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-user"></i>
            {{ user.username }} 
          </button>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">

            <li><a class="dropdown-item" href="#">
              <i class="fa-solid fa-address-card"></i>
              Profile
            </a></li>

            <li><a class="dropdown-item" href="{{ url_for('blog.show_user_posts', username=user.username) }}">
              <i class="fa-regular fa-rectangle-list"></i>
              Posts
            </a></li>

            <li><a class="dropdown-item" href="{{ url_for('blog.new_post') }}">
              <i class="fa-regular fa-square-plus"></i>
              New post
            </a></li>


            <li><hr class="dropdown-divider"></li>

            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">
            <i class="fa-solid fa-arrow-right-from-bracket"></i>
              Sign out</a></li>
          </ul>
        </div>
      </div>
      {% else %}
       <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="btn btn-sm btn-outline-secondary" href="{{ url_for('auth.login') }}">Sign in</a>
        <a class="btn btn-sm btn-outline-secondary mx-1" href="{{ url_for('auth.register') }}">Sign up</a>
      </div>
      {% endif %}

      

    </div>
  </header>

  <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      {% for category in categories %}
          <a class="p-2 link-secondary" href="{{ url_for('blog.show_category', category_id=category.id) }}">{{ category.name }}</a>
      {% endfor %}
    </nav>
  </div>
</div>

<main class="container">

    {% block content %}{% endblock %}

</main>

<div class="container">
<footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
    <div class="col mb-3">
      <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <p class="text-muted">© 2022</p>
    </div>

    <div class="col mb-3">

    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

    <div class="col mb-3">
      <h5>Section</h5>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>
  </footer>
</div>
    
    {% block custom_js %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

</body>
</html>

app/templates/blog/category.html
{% extends './base.html' %}

{% block title %}{% endblock %}

{% block custom_css %}
{% endblock %}

{% block content %}

<div class="row g-5">
  <div class="col-md-8">
    <h3 class="pb-4 mb-4 fst-italic border-bottom">
      {{ category.name }}
    </h3>

    <table id="datatablesSimple" class="table align-middle table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Created at</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Title</th>
          <th>Content</th>
          <th>Created at</th>
          <th>Edit</th>
        </tr>
      </tfoot>
      <tbody>
        {% for post in posts %}
        <tr>
          <td>
            <p class="fw-bold mb-1">{{ post.title }}</p>
          </td>
          <td>{{ post.content | truncate(40, end='...') }}</td>
          <td>
            <p class="fw-normal mb-1">Created at</p>
            <p class="text-muted mb-0">{{ post.created_at }}</p>
          </td>
          <td>
            <a href="{{ url_for('blog.show_post', post_id=post.id) }}" class="btn btn-link btn-sm px-3" data-ripple-color="dark">
              <i class="fa-solid fa-book-open"></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>

  <div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Lorem ipsum dolor sit amet consectetur, adipisicing
          elit. Aperiam omnis veritatis sapiente eaque, voluptates quisquam
          repellat culpa tempore quas velit nulla doloribus quos, iusto neque
          debitis ab aspernatur veniam. Nostrum dolor culpa maxime. Optio hic
          velit pariatur perferendis veritatis ipsa reiciendis labore dolorem
          culpa.</p>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2021</a></li>
          <li><a href="#">February 2021</a></li>
          <li><a href="#">January 2021</a></li>
          <li><a href="#">December 2020</a></li>
          <li><a href="#">November 2020</a></li>
          <li><a href="#">October 2020</a></li>
          <li><a href="#">September 2020</a></li>
          <li><a href="#">August 2020</a></li>
          <li><a href="#">July 2020</a></li>
          <li><a href="#">June 2020</a></li>
          <li><a href="#">May 2020</a></li>
          <li><a href="#">April 2020</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/blog/edit_post.html
{% extends './base.html' %}

{% block title %}{% endblock %}

{% block custom_css %}
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="col-md-12">
    <div
        class="g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative p-3">

        <h1 class="mb-4 fst-italic">Edit post</h1>
        <form method="POST" action="{{ url_for('blog.edit_post', post_id=post.id) }}">
            <div class="form-group mb-1">
                <label for="title">Title:</label>
                <input type="text" class="form-control" id="title" name="title" value="{{ post.title }}"
                    required>
            </div>
            <div class="form-group mb-1">
                <label for="content">Content:</label>
                <textarea class="form-control" id="content" name="content"
                    rows="6"
                    required>{{ post.content }}</textarea>
            </div>
            <div class="form-group mb-4">
                <label for="category">Category:</label>
                <select class="form-control" id="category" name="category"
                    required>
                    <option value disabled>Choise category</option>
                    {% for category in categories %}

                    {% if category.id == post.category_id %}
                        <option value="{{ category.id }}" selected>{{ category.name }}</option>
                    {% else %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endif %}
                    
                   {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-outline-primary">
                <i class="fa-solid fa-check-to-slot"></i>
                Create post</button>
        </form>

    </div>
</div>

{% endblock %}

app/templates/blog/new_post.html
{% extends './base.html' %}

{% block title %}{% endblock %}

{% block custom_css %}
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="col-md-12">
    <div
        class="g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative p-3">

        <h1 class="mb-4 fst-italic">Create new post</h1>
        <form method="POST" action="{{ url_for('blog.new_post') }}">
            <div class="form-group mb-1">
                <label for="title">Title:</label>
                <input type="text" class="form-control" id="title" name="title"
                    required>
            </div>
            <div class="form-group mb-1">
                <label for="content">Content:</label>
                <textarea class="form-control" id="content" name="content"
                    rows="6"
                    required></textarea>
            </div>
            <div class="form-group mb-4">
                <label for="category">Category:</label>
                <select class="form-control" id="category" name="category"
                    required>
                    <option value disabled selected>Choise category</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-outline-primary">
                <i class="fa-solid fa-check-to-slot"></i>
                Create post</button>
        </form>

    </div>
</div>

{% endblock %}

app/templates/blog/post.html
{% extends './base.html' %}

{% block title %}{% endblock %}

{% block custom_css %}
{% endblock %}

{% block content %}

<div class="row g-5">
  <div class="col-md-8">
    <div class="row border-bottom mb-4">
      <div class="col-4 col-sm-6 col-md-8">
        <h3 class="pb-4 fst-italic">
          {{ post.title }}
        </h3>
      </div>

      {% if author.username == user.username %}
      <div class="col-8 col-sm-6 col-md-4">
        <nav class="blog-pagination" aria-label="Pagination">
          <a class="btn btn-outline-primary"
            href="{{ url_for('blog.edit_post', post_id=post.id) }}">
            <i class="fa-regular fa-pen-to-square fa-lg"></i>
            Edit
          </a>
          <a class="btn btn-outline-danger"
            href="{{ url_for('blog.delete_post', post_id=post.id) }}"
            tabindex="-1" aria-disabled="true">
            <i class="fa-solid fa-trash fa-lg"></i>
            Delete
          </a>
        </nav>
      </div>
      {% endif %}

    </div>

    <p>
      {{ post.content }}
    </p>

    <div class="row d-flex justify-content-center">
      <div class="col-md-12">
        <div class="card shadow-0 border" style="background-color: #f0f2f5;">
          <div class="card-body p-4">
            <form class="row" method="post"
              action="{{ url_for('blog.add_comment', post_id=post.id) }}">
              <div class="form-outline col-9 mb-4">
                <input type="text" id="addANote" class="form-control"
                  name="comment" placeholder="Type comment..." />
              </div>
              <div class="col-3">
                <button type="submit" class="btn btn-primary w-100">Add</button>
              </div>
            </form>

            {% for comment in comments %}
            <div class="card mb-4">
              <div class="card-body">
                <p>{{ comment.content }}</p>

                <div class="d-flex justify-content-between">

                  <div class="d-flex flex-row align-items-center">
                    <p class="small mb-0 ms-2">Comment by
                      <a
                        href="{{ url_for('blog.show_user_posts', username=author.username) }}">
                        @{{ comment.author_username }}
                      </a>
                    </p>
                  </div>

                  <div class="d-flex flex-row align-items-center">
                    <p class="small text-muted mb-0">Created at {{ comment.created_at }}</p>
                  </div>

                </div>
              </div>
            </div>
            {% endfor %}

          </div>
        </div>
      </div>
    </div>

  </div>

  <div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">

      <div class="p-4">
        <p class="fw-normal mb-1">Post created at</p>
        <p class="text-muted mb-0">{{ post.created_at }}</p>
        <p class="fw-normal mb-1">By
          <a
            href="{{ url_for('blog.show_user_posts', username=author.username) }}">
            @{{ author.username }}
          </a>
        </p>
      </div>

      <div class="p-4 mb-3 bg-light rounded">
        <h4 class="fst-italic">About</h4>
        <p class="mb-0">Lorem ipsum dolor sit amet consectetur, adipisicing
          elit. Aperiam omnis veritatis sapiente eaque, voluptates quisquam
          repellat culpa tempore quas velit nulla doloribus quos, iusto neque
          debitis ab aspernatur veniam. Nostrum dolor culpa maxime. Optio hic
          velit pariatur perferendis veritatis ipsa reiciendis labore dolorem
          culpa.</p>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Archives</h4>
        <ol class="list-unstyled mb-0">
          <li><a href="#">March 2021</a></li>
          <li><a href="#">February 2021</a></li>
          <li><a href="#">January 2021</a></li>
          <li><a href="#">December 2020</a></li>
          <li><a href="#">November 2020</a></li>
          <li><a href="#">October 2020</a></li>
          <li><a href="#">September 2020</a></li>
          <li><a href="#">August 2020</a></li>
          <li><a href="#">July 2020</a></li>
          <li><a href="#">June 2020</a></li>
          <li><a href="#">May 2020</a></li>
          <li><a href="#">April 2020</a></li>
        </ol>
      </div>

      <div class="p-4">
        <h4 class="fst-italic">Elsewhere</h4>
        <ol class="list-unstyled">
          <li><a href="#">GitHub</a></li>
          <li><a href="#">Twitter</a></li>
          <li><a href="#">Facebook</a></li>
        </ol>
      </div>
    </div>
  </div>
</div>

{% endblock %}

app/templates/blog/user_posts.html
{% extends './base.html' %}

{% block title %}{% endblock %}

{% block custom_css %}
{% endblock %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-primary" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="col-md-12">
  <h3 class="pb-4 mb-4 fst-italic border-bottom">
    {{ user.username }} posts
  </h3>

  <table id="datatablesSimple" class="table align-middle table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Category</th>
        <th>Created at</th>
        <th>View</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Category</th>
        <th>Created at</th>
        <th>View</th>
      </tr>
    </tfoot>
    <tbody>
      {% for post in user_posts %}
      <tr>
        <td>
          <p class="fw-bold mb-1">{{ post.title }}</p>
        </td>
        <td>{{ post.content | truncate(40, end='...') }}</td>
        <td><span class="badge bg-secondary">{{ post.category }}</span></td>
        <td>
          <p class="fw-normal mb-1">Created at</p>
          <p class="text-muted mb-0">{{ post.created_at }}</p>
        </td>
        <td>
          <a href="{{ url_for('blog.show_post', post_id=post.id) }}" class="btn btn-link btn-sm px-3" data-ripple-color="dark">
            <i class="fa-solid fa-book-open"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

{% endblock %}